# MySQL Database
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/edgi_db?useSSL=false
    username: root
    password:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
server:
  port: 8888
